### ISSUE TITLE
Edge Functions are limited to method POST

### ISSUE THREAD

**Issue by Kalzem** [supabase-community/supabase-swift#104]
# Feature request

## Is your feature request related to a problem? Please describe.

I believe Edge Functions should not be limited to POST methods.
There is an official [example](https://github.com/supabase/supabase/blob/master/examples/edge-functions/supabase/functions/restful-tasks/index.ts) of a CRUD edge function.

I have a few functions that rely on GET / PUT methods.

## Describe the solution you'd like

Add a parameter to struct `FunctionInvokeOptions` that would allow to choose the HTTP method from either an enum or a string.

## Additional context

The only workaround I found as of today is to split an edge function that handles GET/PUT/POST/DELETE into 4 functions that ignore the HTTP method.

**Comment by grsouza** [comment]
Hey @Kalzem thanks for opening this issue, that makes sense, I'm going to send a PR fixing this.

Thanks again.

**Comment by bwship** [comment]
Awesome.  I was just about to raise this issue.   I haven't investigated path params working or not, but if you are in there getting http methods working, you might want to look at that too.  for instance, I have an /invitations POST, but then want to also have a /invitations/:id PUT request.  Not sure if it handle that, because I only see the body and headers as able to be set.

**Comment by grsouza** [comment]
Hey @bwship you can use as following:

```swift
try await supabase.functions.invoke(
    "invitations/\(id)",
    options: .init(method: .put)
)
```
