### ISSUE TITLE
Please introduce tags

### ISSUE THREAD

**Issue by chFlorian** [supabase-community/supabase-swift#16]
Please introduce tags and releases to this package. As you know Swift Playgrounds 4 got released, but it only supports SPM packages by version number, not by branch. Thus it is currently impossible to use this SDK in a Playgrounds project.

**Comment by samjproctor** [comment]
I absolutely second this request. Versioning tags are missing for supabase, and from what I can see are the only thing stopping this from being usable in swift playgrounds.
Further to this, no BAAS can be used because although they have swift packages, they are wrappers for C++ code, which cannot be used in swift playgrounds. This seems to be the only package solely written in swift.  
Admittedly not a big market here, but unless I am much mistaken, this should be 10 minute update for somebody to change. 
Thanks for the top work

**Comment by grsouza** [comment]
Tag created [`0.0.1`](https://github.com/supabase-community/supabase-swift/releases/tag/0.0.1).
