### ISSUE TITLE
Allow inserting null values

### ISSUE THREAD

**Issue by Magnuti** [supabase-community/supabase-swift#203]
Having a table that looks like this

```
CREATE TABLE IF NOT EXISTS "public"."items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "name" "uuid"
);
```

It should be possible to write

```swift
let toInsert = items.map { item in
    InsertDTO(
        user_id: userId,
        name: item.name, // Can be nil
    )
}

try await supabaseClient.database.from("items")
    .insert(toInsert)
    .execute()
```

However this is not possible since I get the error `invalid input syntax for type uuid: "NULL"`.

My solution has been to insert twice; once for the items with `name` present and once for the items with `name` as `nil`. But this does not seem optimal.

**Comment by grdsdev** [comment]
Hi @Magnuti I made a few tests and found that:

1. It seems you're sending an invalid value for the `name` field, which is defined as a `uuid` type, and you're sending a `"NULL"` (string with NULL value), which is an invalid UUID, that is what the errors say and what I was able to reproduce on my side.

2. The library currently doesn't support sending an `Array` with a different set of fields, for example:
```json
[
  {
    "user_id": "6ABCF0F6-FBA1-4139-A00E-42C3B32DFA15"
  },
  {
    "name": "B47258FD-C481-4602-A7B4-0A33DC68F9A9",
    "user_id": "6ABCF0F6-FBA1-4139-A00E-42C3B32DFA15"
  }
]
```

That happens because `JSONEncoder` omits `null` values by default, if you want to include them, you need to implement `Encodable` manually as instructed here (https://stackoverflow.com/questions/47266862/encode-nil-value-as-null-with-jsonencoder).

I'll add an implementation of the `NullEncodable` property wrapper in the library, to overcome this limitation, and add some documentation about it.

I hope this helps you, if you have any questions, please let me know.
