### ISSUE TITLE
Can't sign in another google account

### ISSUE THREAD

**Issue by nanghuy** [supabase-community/supabase-swift#32]
When I login with goggle account, after signOut I can't sign in another google account. Step flow:
- Login with google account using: SPBase.shared.client.auth.signIn(provider: .google, options: options) 
- SignOut using: SPBase.shared.client.auth.signOut()
- When login with google account again:

**Expected**: Show login screen with allow input new account

![Simulator Screen Shot - iPhone 8 - 2022-06-28 at 17 08 07](https://user-images.githubusercontent.com/7701515/176153646-41ca89ae-b0e2-4a8c-83bf-89b00f9b3c50.png)

**Actual**: Auto login with old account

**Comment by grsouza** [comment]
Hi @nanghuy I don't know if I correctly understood the issue here.

The signed account in the browser is handled by the browser and has nothing to do with the library., maybe Safari is holding a session and that's why it isn't prompting for credentials, but It should have an option for selecting a different account.

I've added an example on how to integrating Google Sign in using `gotrue-swift`, check it out https://github.com/supabase-community/gotrue-swift/tree/main/Examples

On my tests I was able to choose a different account for signing in, so I assume there's no issue on the library itself.

I'll close this for now, but feel free to re-open it if you still think there is an issue.

Thanks!
