### ISSUE TITLE
[tvOS] Allow setting auth tokens manually

### ISSUE THREAD

**Issue by florivdg** [supabase-community/supabase-swift#37]
We are developing a digital signage app for Apple TV (tvOS) and are considering to use Supabase as our backend service. While creating a proof of concept I stumbled upon a problem with authenticating. Since there is no web browser on tvOS the traditional auth flow won't work.

Instead the user needs to sign in on another device and we need to set auth tokens manually on the `SupabaseClient` instance in our tvOS app. E.g. there might be a companion sign-in app on iOS that transfers auth tokens securely over to the tvOS app.  
But as of now there is no way to set auth tokens manually on the client itself.

In `supabase-js` we have a method called `setAuth()` that lets you override the access token. Since the app basically does not have any user interaction at all, we also need to set the refresh token in order to stay authenticated while the app shows its content.

**Comment by grsouza** [comment]
Hi @florivdg thanks for opening this issue.

Would this methods on `gotrue-js` https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L386-L421 solve your issue if added to `gotrue-swift`?

**Comment by florivdg** [comment]
Hey @grsouza thanks for your quick response!

Indeed I think this is exactly what I am looking for in order to get this to work!

**Comment by grsouza** [comment]
Ok, the method for setting refresh token is already implemented on `gotrue-swift`, it just lacks the `setAuth`.

If this is urgent for you, I think it would be faster if you could PR this change into the `gotrue-swift` repository, and I'd be glad reviewing it.

If that's not blocking you now, I can do it tomorrow I think.

**Comment by matthewmorek** [comment]
I have a similar problem, however not on tvOS, but while developing an iOS App Extension for my iOS app. There's currently no mechanism in `supabase-swift` to authenticate a new session using existing (unexpired) `accessToken` and `refreshToken`; however this functionality [seem to exists in the `gotrue-js`](https://github.com/supabase/gotrue-js/issues/406#issuecomment-1279697950), as per comment in the linked thread.

This is due to the fact that iOS App Extensions, despite being part of the same app bundle live in separate containers that do not have access to one another.

#### A simple case to make sure it's clear why this is needed on iOS:
1. User launches `MainApp` and signs in using email and password
2. User then switches to another app, for example Safari
3. User finds a link they want to share to their `MainApp` account, so they tap `Share` button and open iOS Share Sheet
4. User sees `MainApp` and taps the icon to share it.
5. iOS fires up `MainApp.ShareExtension` bundle and in order to execute writing data directly to Supabase using `supabase-swift`

#### Expected outcomes:
- App Extension re-authenticates if necessary before it can upload data to Supabase via SDK using existing credentials from the `MainApp`
- User is never asked for credentials, unless the session in the `MainApp` is invalid or expired

#### Current outcomes:
- Unable to re-authenticate reusing existing session without logging user out from MainApp

#### Current workaround:
- Use CoreData with a Shared Container to add data to `MainApp` with a massive overhead to sync this data accurately when the `MainApp` is re-opened, so it's not feasible at all to do this.

#### Notes:
- App is online-only (not offline capability, storage, or sync; just in-memory), so relies 100% on Supabase SDK

**Comment by grsouza** [comment]
Hey all, I implemented the `setSession` method on https://github.com/supabase-community/gotrue-swift/pull/36
Can someone point to `feat/setSession` and test if it solves your use case?
